#!/bin/sh
#
# Solaris rc3 script for EPICS CA gateway
#

if [ $1 = "start" ]; then
	if [ -x /home/helios/GATEWAY/gateway/gateway ]; then
		echo "Starting EPICS CA gateway "
		/home/helios/GATEWAY/gateway/gateway -log gateway.log -cip 164.54.3.255 -sip 164.54.188.65 -home /home/helios/GATEWAY/gateway -uid 265 -server
        fi
else
        if [ $1 = "stop" ]; then
                echo "Stopping EPICS CA gateway "
                /home/helios/GATEWAY/gateway/gateway.killer
        fi
fi

