TOP=..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

runtests:
	./runTests.py

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

